### PR TITLE
NodeCollaborator class[WIP]

### PR DESCRIPTION
**Pull request by mohitmun**
First of all, Thanks a lot for this project. This was badly needed.

I'm reluctant to use my personal account for this project(fear of getting blocked by google).
So better approach is creating fake account and for each note, add yourself as collaborator and keep updating it.
I have added NodeCollaborator class which handles this

Test are pending. Will add few test cases in sometime.
Let me know if I miss anything

### CODE REVIEW

**Comment by kiwiz** [comment]
Hi, thanks for the PR! I've been doing this manually, so having this functionality built in is terrific.

I'm a bit concerned about the fact that the input and output (`roleInfo` vs shareRequests`) differ. I'm working on a [project](https://github.com/kiwiz/keep-cli) which serializes state to disk for offline mode (and faster load times). I think the `load` method needs to parse the `shareRequests` field, to preserve this functionality across runs of the application. If you've any other ideas, I'd love to hear them too. Lemme know when you're ready with this PR and I'll merge it.

**Comment by kiwiz** [comment]
* Feel free to ignore that codeclimat failure.

**Comment by mohitmun** [comment]
@kiwiz I have added tests.

> I think the load method needs to parse the shareRequests field

I didn't this part. also I need to get familiarize with code. I just inspected few requests and made this work :P  Let me know if I miss anything

**Comment by kiwiz** [comment]
Merged, thanks!

**Pull request merged**
